### ISSUE TITLE
How to implement this in an app

### ISSUE THREAD

**Issue by aleBiagini** [dotnet/AspNetCore.Docs.it-it#46]
Hello, 
It's not very clear how to implement the authentication cookie into an app.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Usa autenticazione cookie senza ASP.NET Core identità](https://docs.microsoft.com/it-it/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @aleBiagini
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @aleBiagini, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17585. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
