### ISSUE TITLE
GPDR on mobile problems

### ISSUE THREAD

**Issue by mtugnoli** [dotnet/AspNetCore.Docs.it-it#48]
I see the GDPR sample for asp.net core, but I don't understand why don't run on mobile !
this row seem have problems,
can you help me ?

document.cookie = button.dataset.cookieString;

[Immetti qui i commenti]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [Supporto di Regolamento generale sulla protezione dei dati (GDPR) in ASP.NET Core](https://docs.microsoft.com/it-it/aspnet/core/security/gdpr?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @mtugnoli
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @mtugnoli, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17663. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
