### ISSUE TITLE
Classic method for DataAnnotations Localization

### ISSUE THREAD

**Issue by GioviQ** [dotnet/AspNetCore.Docs.it-it#49]
I verified in my blazor app, that the classic localization method is still working. E.g.:

[StringLength(64, ErrorMessageResourceType = typeof(Strings), ErrorMessageResourceName = "ErrorInvalidLength", MinimumLength = 2)]
        [RegularExpression(@"[^\s]+", ErrorMessageResourceType = typeof(Strings), ErrorMessageResourceName = "SpacesNotPermitted")]
        [Display(Name = "UserName", ResourceType = typeof(Strings))]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalizzazione e localizzazione in ASP.NET Core](https://docs.microsoft.com/it-it/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @GioviQ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @GioviQ, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17738. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
