### ISSUE TITLE
I would like back the option to have the original text in english.

### ISSUE THREAD

**Issue by GioviQ** [dotnet/AspNetCore.Docs.it-it#53]
I would like back the option to have the original text in english.

**Comment by srvbpigh** [comment]
Hello, @GioviQ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @GioviQ 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by GioviQ** [comment]
@CeciAc Some months ago in the automatically translated doc pages  there was a button to restore the original english version. Do you remember?

**Comment by CeciAc** [comment]
@JasonCard can you please check this issue?

**Comment by JasonCard** [comment]
Hi @GioviQ

Thank you for your feedback.
The "Read in English" toggle option should be available in most pages. 
Currently, it's not working on certain pages and we are working to resolving that issue.
All affected pages should be resolved by end of next week.
If you'd like to share the specific page where it's not working, then I can help to follow up.
For now, I'll close this issue and please feel free to re-open with URL for the specific page.

Best regards,
Jason
cc CeciAc
