### ISSUE TITLE
Authentication service support should be better detailed

### ISSUE THREAD

**Issue by ciacco85** [dotnet/AspNetCore.Docs.it-it#54]
---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 9816eaee-5eff-c3c8-5d58-e2c02c760a00
* Version Independent ID: 60992d09-2a04-1d10-4c85-9642b20ff0e3
* Content: [Proteggere un' Blazor app ospitata ASP.NET Core webassembly con Azure Active Directory](https://docs.microsoft.com/it-it/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @ciacco85
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @ciacco85, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/18791. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
